const hostUrl="http://api.planetshare.in/public/api/website";
 const hostUrld="http://api.planetshare.in/public/api/dashboard";
//const hostUrl="http://localhost/Shantanu_project/OTT_LIVE_WORK/LARAVEL_WORK/PlanetShare1/public/api/website";
 //const hostUrld="http://localhost/Shantanu_project/OTT_LIVE_WORK/LARAVEL_WORK/PlanetShare1/public/api/dashboard";
export const IP="http://api.planetshare.in";
export const LOGIN=hostUrl+"/signin";
export const CHUNK_UPLOAD_SERVICE=hostUrld+"/upload";
export const REGISTER=hostUrl+"/register";
export const PHONELOGIN=hostUrl+"/otp";
export const VERIFYOTP=hostUrl+"/verifyotp";
export const SOCIALLOGIN=hostUrl+"/sociallogin";
export const VIDEOLIST=hostUrl+"/videos_desc";
export const VIDEOLIST_EDIT=hostUrld+"/videos_desc/edit";
export const VIDEO_CHANGESTATUS=hostUrld+"/videos_desc/changeStatus";
export const VIDEO_SEARCH=hostUrl+"/search";
export const VIDEOS=hostUrld+"/videos";
export const VIDEO_DESCRIPTION=hostUrld+"/videos_desc/save";
export const VIDEO_DESCRIPTION_EDIT=hostUrld+"/videos_desc/edit";
export const USER_CART=hostUrl+"/cart/add";
export const VIDEO_DUBB=hostUrl+"/dubb";
export const VIDEO_DUBB_PREVIEW=hostUrld+"/dubb/singleRecord";
export const DUBBED_ORDERS=hostUrl+"/dubbstatus";
export const PAYMENT=hostUrl+"/dubb/doPayment";
export const DUBBED_VIDEO_DOWNLOAD=hostUrl+"/dubb/download";
export const SUBTITLE_VIDEO_DOWNLOAD=hostUrl+"/subtitle/download"
export const TRANSCODE_VIDEO_DOWNLOAD=hostUrl+"/transcode/download"
export const TAGGING_VIDEO_DOWNLOAD=hostUrl+"/tagging/download"
export const VIDEO_TRANSCODE=hostUrl+"/transcode";
export const VIDEO_TAGGING=hostUrl+"/autoTag";
export const VIDEO_SUBTITLING=hostUrl+"/subtitle";
export const TRANSCODE_ORDERS=hostUrl+"/transcodestatus";
export const TAGGING_ORDERS=hostUrl+"/autotagstatus";
export const SUBTITLE_ORDERS=hostUrl+"/subtitlestatus";
export const TRANSCODE_HOME=hostUrl+"/transcode/home";
export const SUBTITLE_HOME=hostUrl+"/subtitle/home";
export const TAGGING_HOME=hostUrl+"/tagging/home";
export const DUBB_HOME=hostUrl+"/dubb/home";
export const VIDEO_TRANSCODE_PREVIEW=hostUrld+"/transcode/singleRecord";
export const VIDEO_SUBTITLE_PREVIEW=hostUrld+"/subtitle/singleRecord";
export const VIDEO_TAGGING_PREVIEW=hostUrld+"/tagging/singleRecord";

// ---------  VENDOR SECTIOn -----------------
export const VENDOR_REGISTRATION=hostUrl+"/vendor/registration";
export const CHECK_VENDOR_STATUS=hostUrl+"/vendor/checkVendor";
export const ADD_VENDOR_SERVICE=hostUrl+"/vendor/addServices";
export const CHANGE_VENDOR_STATUS=hostUrl+"/vendorjob/changeStatus";
export const VENDOR_VIDEO_DOWNLOAD=hostUrl+"/vendorjob/download";
export const LIST_VENDOR_JOBS=hostUrl+"/vendor/jobLists";
export const VENDOR_SINGLE_JOB=hostUrl+"/vendor/singleJobDetails";
export const VENDOR_SERVICE_LIST=hostUrl+"/vendor/serviceLists";
export const VENDOR_ADDED_SERVICE_LIST=hostUrl+"/vendor/checkAddedService";
export const VENDOR_PROFILE=hostUrl+"/vendor/profile";
export const VENDOR_UPDATE_PROFILE=hostUrl+"/vendor/updateProfile";
export const VENDOR_PAYMENT_PAGE=hostUrl+"/vendor/paymentOverview";
export const VENDOR_SERVICE_COUNT=hostUrl+"/vendor/ServiceCount";
export const VENDOR_SINGLE_JOB_DETAILS=hostUrld+"/vendor/singleRecord"
export const VENDOR_DELETE_SERVICE=hostUrl+"/vendor/delete"
export const VENDOR_SERVICE_EDIT=hostUrl+"/vendor/editService";
export const VENDOR_SERVICE_UPDATE=hostUrl+"/vendor/updateService";
export const VENDOR_SERVICE_REQUEST_ANALYTICS=hostUrl+"/vendor/analytics";
// -------------  SELLER SECTION ---------------//
export const SELLER_REGISTRATION=hostUrl+"/seller/registration";
export const CHECK_SELLER_STATUS=hostUrl+"/seller/checkSeller";
export const SELLER_PROFILE=hostUrl+"/seller/profile";
export const SELLER_UPDATE_PROFILE=hostUrl+"/seller/updateProfile";
export const SELLER_SERVICE_COUNT=hostUrl+"/seller/ServiceCount";
export const SELLER_SERVICE_REQUEST_ANALYTICS=hostUrl+"/seller/analytics";
export const SELLER_LIST_EDIT=hostUrld+"/videos_desc/edit";
export const SELLER_LIST_UPDATE_DATA=hostUrl+"/seller/editVideoDesc";

//_---------------- LOGOUT -------------///
export const LOGOUT=hostUrld+"/logout";
export const CONTACTUS=hostUrl+"/contact";
